name: Release

on:
  push:
    branches:
      - main
      - alpha
      - beta
      - next
      - 'next-major'
      - '[0-9]+.x'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: docker://ghcr.io/codfish/semantic-release-action@sha256:4c0955361cf42e5ab9bb05df3a1e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
