name: Release

on:
  push:
    branches:
      - main
      - alpha
      - beta
      - next
      - next-major
      - '[0-9]+.x'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: docker://ghcr.io/codfish/semantic-release-action@sha256:4c0955361cf42e5ab9bb05df3a1e2a781c443f9760b63a68957689445051a2fb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
